language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pytest coverage header2whatever pytest-cov
  - python setup.py sdist
  - "pip install dist/robotpy-ctre-*.tar.gz"
script:
  - RUNCOVERAGE=1 tests/run_tests.sh

jobs:
  include:

  # Check to see if the compilation succeeds
  - python: "3.7"
    install:
    - FORCE_HAL_INSTALL=1 pip install pybind11 header2whatever robotpy-hal-roborio
    script:
    - TRAVIS_BUILD=1 python setup.py sdist build
  
  - stage: format-check
    python:
    - "3.6"
    install:
    - pip install black
    script:
    - black --check --diff .

  
  - stage: deploy-pypi
    python: "3.6"
    if: tag IS present
    install:
    - pip install header2whatever
    script: skip
    deploy:
    - provider: pypi
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
