---

classes:
  StatorCurrentLimitConfiguration:
    shared_ptr: true
    attributes:
      enable:
      currentLimit:
      triggerThresholdCurrent:
      triggerThresholdTime:
    methods:
      StatorCurrentLimitConfiguration:
        overloads:
          "":
          double*, int:
            ignore: true  # unsafe array
          bool, double, double, double:
      ToString:
        rename: __str__
      ToArray:
      Deserialize:
        ignore: true
      Equals:
        rename: __eq__
